<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
    <NoWarn>CA1305;CA1826,CA1822;CA1859;CA1869;CA1707;CA1861</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Salep.ClientGenerator\Salep.ClientGenerator.csproj" />
  </ItemGroup>
</Project>
