// <auto-generated/>
#nullable enable
using System.Text.Json;
using Xunit;
using Salep.Samples.Opinionated.Scriban.Client;

using Salep.Samples.Opinionated.Scriban.ModuleClient;

namespace Salep.Samples.Opinionated.Scriban.ModuleClient.Tests;

public sealed class UnionConverterTests
{
    [Fact]
    public void SearchResult_Deserializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<SearchResult>("""{"__typename":"User"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void SearchResult_Deserializes_Post()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<SearchResult>("""{"__typename":"Post"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void SearchResult_Deserializes_Comment()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<SearchResult>("""{"__typename":"Comment"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void SearchResult_Write_Serializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var value = JsonSerializer.Deserialize<SearchResult>("""{"__typename":"User"}""", options);
        var json = JsonSerializer.Serialize(value, options);

        Assert.False(string.IsNullOrWhiteSpace(json));
    }

    [Fact]
    public void SearchResult_Read_Returns_Null_When_Json_Null()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<SearchResult?>("null", options);
        Assert.Null(result);
    }

    [Fact]
    public void SearchResult_Read_Throws_When_Typename_Missing()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        Assert.Throws<JsonException>(() => JsonSerializer.Deserialize<SearchResult>("{\"id\":\"sample\"}", options));
    }

    [Fact]
    public void SearchResult_Read_Throws_When_Typename_Unknown()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        Assert.Throws<JsonException>(() => JsonSerializer.Deserialize<SearchResult>("{\"__typename\":\"Unknown\"}", options));
    }

    [Fact]
    public void AccountResult_Deserializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<AccountResult>("""{"__typename":"User"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void AccountResult_Write_Serializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var value = JsonSerializer.Deserialize<AccountResult>("""{"__typename":"User"}""", options);
        var json = JsonSerializer.Serialize(value, options);

        Assert.False(string.IsNullOrWhiteSpace(json));
    }

    [Fact]
    public void NamedResult_Deserializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<NamedResult>("""{"__typename":"User"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void NamedResult_Write_Serializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var value = JsonSerializer.Deserialize<NamedResult>("""{"__typename":"User"}""", options);
        var json = JsonSerializer.Serialize(value, options);

        Assert.False(string.IsNullOrWhiteSpace(json));
    }

    [Fact]
    public void NodeResult_Deserializes_Comment()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<NodeResult>("""{"__typename":"Comment"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void NodeResult_Deserializes_Post()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<NodeResult>("""{"__typename":"Post"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void NodeResult_Deserializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<NodeResult>("""{"__typename":"User"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void NodeResult_Write_Serializes_Comment()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var value = JsonSerializer.Deserialize<NodeResult>("""{"__typename":"Comment"}""", options);
        var json = JsonSerializer.Serialize(value, options);

        Assert.False(string.IsNullOrWhiteSpace(json));
    }

    [Fact]
    public void TimestampedResult_Deserializes_Comment()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<TimestampedResult>("""{"__typename":"Comment"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void TimestampedResult_Deserializes_Post()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<TimestampedResult>("""{"__typename":"Post"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void TimestampedResult_Deserializes_User()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var result = JsonSerializer.Deserialize<TimestampedResult>("""{"__typename":"User"}""", options);
        Assert.NotNull(result);
    }

    [Fact]
    public void TimestampedResult_Write_Serializes_Comment()
    {
        var options = new JsonSerializerOptions();
        global::Salep.Samples.Opinionated.Scriban.Client.UnionJsonConverters.Register(options);
        global::Salep.Samples.Opinionated.Scriban.ModuleClient.UnionJsonConverters.Register(options);
        UnionJsonConverters.Register(options);
        var value = JsonSerializer.Deserialize<TimestampedResult>("""{"__typename":"Comment"}""", options);
        var json = JsonSerializer.Serialize(value, options);

        Assert.False(string.IsNullOrWhiteSpace(json));
    }

}
