<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SalepConfigFile>salep.json</SalepConfigFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../Client/Salep.Samples.MinimalDependencies.Scriban.Client.csproj" />
    <PackageReference Include="Salep.ClientGenerator" PrivateAssets="all" />
  </ItemGroup>
</Project>
