<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dunet" />
        <PackageReference Include="NodaTime" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="Salep.ClientGenerator" PrivateAssets="all" />
    </ItemGroup>

</Project>
