// <auto-generated/>
#nullable enable
using System;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using GraphQL.Sharp.Generated;
using AccountResult = global::GraphQL.Sharp.Generated.AccountResult;
using Comment = global::GraphQL.Sharp.Generated.Comment;
using CreatePostInput = global::GraphQL.Sharp.Generated.CreatePostInput;
using IAccount = global::GraphQL.Sharp.Generated.IAccount;
using INamed = global::GraphQL.Sharp.Generated.INamed;
using INode = global::GraphQL.Sharp.Generated.INode;
using ITimestamped = global::GraphQL.Sharp.Generated.ITimestamped;
using MetadataInput = global::GraphQL.Sharp.Generated.MetadataInput;
using Mutation = global::GraphQL.Sharp.Generated.Mutation;
using NamedResult = global::GraphQL.Sharp.Generated.NamedResult;
using NodeResult = global::GraphQL.Sharp.Generated.NodeResult;
using Post = global::GraphQL.Sharp.Generated.Post;
using Query = global::GraphQL.Sharp.Generated.Query;
using Role = global::GraphQL.Sharp.Generated.Role;
using SearchInput = global::GraphQL.Sharp.Generated.SearchInput;
using SearchResult = global::GraphQL.Sharp.Generated.SearchResult;
using Subscription = global::GraphQL.Sharp.Generated.Subscription;
using TimestampedResult = global::GraphQL.Sharp.Generated.TimestampedResult;
using User = global::GraphQL.Sharp.Generated.User;
using UserFilter = global::GraphQL.Sharp.Generated.UserFilter;

namespace Salep.Samples.MinimalDependencies.Module.Tests;
internal sealed class TestHttpMessageHandler : HttpMessageHandler
{
    private readonly Func<HttpRequestMessage, HttpResponseMessage> _handler;
    public TestHttpMessageHandler(Func<HttpRequestMessage, HttpResponseMessage> handler)
    {
        _handler = handler;
    }

    public HttpRequestMessage? LastRequest { get; private set; }
    public string? ContentText { get; private set; }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        LastRequest = request;
        ContentText = request.Content is null ? null : request.Content.ReadAsStringAsync(cancellationToken).GetAwaiter().GetResult();
        return Task.FromResult(_handler(request));
    }

    public static HttpResponseMessage JsonResponse(string json)
    {
        return new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(json)
        };
    }
}
