// <auto-generated/>
#nullable enable
using Xunit;
using Salep.Samples.MinimalDependencies.Scriban.Client;

namespace Salep.Samples.MinimalDependencies.Scriban.Client.Tests;

public sealed class OperationsMetadataTests
{
    [Fact]
    public void CreatePostSimple_Operation_Metadata()
    {
        var variables = new CreatePostSimpleVariables();
        var response = new CreatePostSimpleResponse();
        var operation = new CreatePostSimpleOperation(variables);
        Assert.Equal("CreatePostSimple", operation.OperationName);
        Assert.Contains("CreatePostSimple", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void CreatePostWithContent_Operation_Metadata()
    {
        var variables = new CreatePostWithContentVariables();
        var response = new CreatePostWithContentResponse();
        var operation = new CreatePostWithContentOperation(variables);
        Assert.Equal("CreatePostWithContent", operation.OperationName);
        Assert.Contains("CreatePostWithContent", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void CreatePostAliased_Operation_Metadata()
    {
        var variables = new CreatePostAliasedVariables();
        var response = new CreatePostAliasedResponse();
        var operation = new CreatePostAliasedOperation(variables);
        Assert.Equal("CreatePostAliased", operation.OperationName);
        Assert.Contains("CreatePostAliased", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void UpdatePostWithDefaults_Operation_Metadata()
    {
        var variables = new UpdatePostWithDefaultsVariables();
        var response = new UpdatePostWithDefaultsResponse();
        var operation = new UpdatePostWithDefaultsOperation(variables);
        Assert.Equal("UpdatePostWithDefaults", operation.OperationName);
        Assert.Contains("UpdatePostWithDefaults", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void DeletePosts_Operation_Metadata()
    {
        var variables = new DeletePostsVariables();
        var response = new DeletePostsResponse();
        var operation = new DeletePostsOperation(variables);
        Assert.Equal("DeletePosts", operation.OperationName);
        Assert.Contains("DeletePosts", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void UsersDefaultRole_Operation_Metadata()
    {
        var variables = new UsersDefaultRoleVariables();
        var response = new UsersDefaultRoleResponse();
        var operation = new UsersDefaultRoleOperation(variables);
        Assert.Equal("UsersDefaultRole", operation.OperationName);
        Assert.Contains("UsersDefaultRole", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void UsersByRole_Operation_Metadata()
    {
        var variables = new UsersByRoleVariables();
        var response = new UsersByRoleResponse();
        var operation = new UsersByRoleOperation(variables);
        Assert.Equal("UsersByRole", operation.OperationName);
        Assert.Contains("UsersByRole", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void UsersByRole_Omits_Variable_Definition()
    {
        var operation = new UsersByRoleOperation(null);
        Assert.DoesNotMatch("\\$ids(?![_0-9A-Za-z])", operation.Query);
    }

    [Fact]
    public void SearchUsersAndPosts_Operation_Metadata()
    {
        var variables = new SearchUsersAndPostsVariables();
        var response = new SearchUsersAndPostsResponse();
        var operation = new SearchUsersAndPostsOperation(variables);
        Assert.Equal("SearchUsersAndPosts", operation.OperationName);
        Assert.Contains("SearchUsersAndPosts", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void NodeById_Operation_Metadata()
    {
        var variables = new NodeByIdVariables();
        var response = new NodeByIdResponse();
        var operation = new NodeByIdOperation(variables);
        Assert.Equal("NodeById", operation.OperationName);
        Assert.Contains("NodeById", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void SearchWithMultipleInlineFragments_Operation_Metadata()
    {
        var variables = new SearchWithMultipleInlineFragmentsVariables();
        var response = new SearchWithMultipleInlineFragmentsResponse();
        var operation = new SearchWithMultipleInlineFragmentsOperation(variables);
        Assert.Equal("SearchWithMultipleInlineFragments", operation.OperationName);
        Assert.Contains("SearchWithMultipleInlineFragments", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void EchoList_Operation_Metadata()
    {
        var variables = new EchoListVariables();
        var response = new EchoListResponse();
        var operation = new EchoListOperation(variables);
        Assert.Equal("EchoList", operation.OperationName);
        Assert.Contains("EchoList", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void EchoList_Omits_Variable_Definition()
    {
        var operation = new EchoListOperation(null);
        Assert.DoesNotMatch("\\$single(?![_0-9A-Za-z])", operation.Query);
        Assert.DoesNotMatch("\\$options(?![_0-9A-Za-z])", operation.Query);
    }

    [Fact]
    public void PostsByIds_Operation_Metadata()
    {
        var variables = new PostsByIdsVariables();
        var response = new PostsByIdsResponse();
        var operation = new PostsByIdsOperation(variables);
        Assert.Equal("PostsByIds", operation.OperationName);
        Assert.Contains("PostsByIds", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void UnusedVar_Operation_Metadata()
    {
        var variables = new UnusedVarVariables();
        var response = new UnusedVarResponse();
        var operation = new UnusedVarOperation(variables);
        Assert.Equal("UnusedVar", operation.OperationName);
        Assert.Contains("UnusedVar", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void UnusedVar_Omits_Variable_Definition()
    {
        var operation = new UnusedVarOperation(null);
        Assert.DoesNotMatch("\\$unused(?![_0-9A-Za-z])", operation.Query);
    }

    [Fact]
    public void PostCreatedFull_Operation_Metadata()
    {
        var variables = new PostCreatedFullVariables();
        var response = new PostCreatedFullResponse();
        var operation = new PostCreatedFullOperation(variables);
        Assert.Equal("PostCreatedFull", operation.OperationName);
        Assert.Contains("PostCreatedFull", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void PostCreatedMinimal_Operation_Metadata()
    {
        var variables = new PostCreatedMinimalVariables();
        var response = new PostCreatedMinimalResponse();
        var operation = new PostCreatedMinimalOperation(variables);
        Assert.Equal("PostCreatedMinimal", operation.OperationName);
        Assert.Contains("PostCreatedMinimal", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void CommentAdded_Operation_Metadata()
    {
        var variables = new CommentAddedVariables();
        var response = new CommentAddedResponse();
        var operation = new CommentAddedOperation(variables);
        Assert.Equal("CommentAdded", operation.OperationName);
        Assert.Contains("CommentAdded", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
}
