// <auto-generated/>
#nullable enable
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Xunit;
using Salep.Samples.MinimalDependencies.Scriban.Client;
namespace Salep.Samples.MinimalDependencies.Scriban.Client.Tests;

public sealed class OperationsResponseTests
{
    [Fact]
    public async Task CreatePostSimple_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"createPost":{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.CreatePostSimpleAsync(new CreatePostSimpleVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task CreatePostWithContent_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"createPost":{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.CreatePostWithContentAsync(new CreatePostWithContentVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task CreatePostAliased_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"first":{"id":"sample","title":"sample"},"second":{"id":"sample","title":"sample","content":"sample"}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.CreatePostAliasedAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task UpdatePostWithDefaults_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"updatePost":{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.UpdatePostWithDefaultsAsync(new UpdatePostWithDefaultsVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task DeletePosts_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"deleted":[{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.DeletePostsAsync(new DeletePostsVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task UsersDefaultRole_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"users":[{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.UsersDefaultRoleAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task UsersByRole_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"admins":[{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z","posts":[{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}]}],"guests":[{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.UsersByRoleAsync(new UsersByRoleVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task SearchUsersAndPosts_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"search":[{"__typename":"User","id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.SearchUsersAndPostsAsync(new SearchUsersAndPostsVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task NodeById_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"byId":{"__typename":"Comment","id":"sample","body":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.NodeByIdAsync(new NodeByIdVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task SearchWithMultipleInlineFragments_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"results":[{"__typename":"User","id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z","posts":[{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}]}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.SearchWithMultipleInlineFragmentsAsync(new SearchWithMultipleInlineFragmentsVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task EchoList_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"echoed":["sample"]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.EchoListAsync(new EchoListVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task PostsByIds_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"posts":[{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.PostsByIdsAsync(new PostsByIdsVariables(), TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task UnusedVar_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"users":[{"id":"sample"}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.UnusedVarAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task PostCreatedFull_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"postCreated":{"id":"sample","title":"sample","content":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.PostCreatedFullAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task PostCreatedMinimal_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"postCreated":{"id":"sample","title":"sample"}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.PostCreatedMinimalAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task CommentAdded_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"commentAdded":{"id":"sample","body":"sample","author":{"id":"sample","name":"sample","role":"GUEST","createdAt":"1970-01-01T00:00:00Z"}}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLOperations(client);
        var response = await api.CommentAddedAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
}
