<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Salep.ClientGenerator" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Salep.Samples.MinimalDependencies.Client\Salep.Samples.MinimalDependencies.Client.csproj" />
    </ItemGroup>

</Project>
