<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>PACKAGE-README.md</PackageReadmeFile>
    <PackageId>Salep.Parser</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../docs/package-readme.md" Pack="true" PackagePath="/" PackageReadmeFile="true" />
  </ItemGroup>
</Project>
