<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GraphQLParser</RootNamespace>
    <AssemblyName>GraphQLParser</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>PACKAGE-README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../docs/package-readme.md" Pack="true" PackagePath="/" PackageReadmeFile="true" />
  </ItemGroup>
</Project>
