// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Xunit;
using Salep.Samples.MinimalDependencies.Client;

namespace Salep.Samples.MinimalDependencies.Client.Tests;

internal sealed record DummyResponse;
internal sealed record DummyVariables(string Value);
internal sealed record DummyUser;
internal sealed record DummyUsersResponse(DummyUser[]? Users);
internal sealed record DummyListResponse(List<string?>? Posts);

internal sealed record DummyOperation(bool IsQuery, DummyVariables? Variables) : global::Salep.Samples.MinimalDependencies.Client.IGraphQLOperation<DummyResponse, DummyVariables>
{
    public string OperationName => "TestOp";
    public string Query => IsQuery ? "query TestOp { __typename }" : "mutation TestOp { __typename }";
}

public sealed class GraphQLClientPayloadTests
{
    [Fact]
    public async Task ExecuteAsync_SerializesOperationPayload()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var operation = new DummyOperation(false, new DummyVariables("value"));
        _ = await client.ExecuteAsync(operation, TestContext.Current.CancellationToken);
        using var document = JsonDocument.Parse(handler.ContentText!);
        Assert.Equal("TestOp", document.RootElement.GetProperty("operationName").GetString());
        Assert.Contains("TestOp", document.RootElement.GetProperty("query").GetString());
        Assert.Equal("value", document.RootElement.GetProperty("variables").GetProperty("value").GetString());
    }
    [Fact]
    public async Task ExecuteAsync_Omits_Null_Variables()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        _ = await client.ExecuteAsync(new DummyOperation(false, null), TestContext.Current.CancellationToken);
        using var document = JsonDocument.Parse(handler.ContentText!);
        Assert.False(document.RootElement.TryGetProperty("variables", out _));
    }
    [Fact]
    public async Task ExecuteAsync_Uses_Get_For_Query()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        _ = await client.ExecuteAsync(new DummyOperation(true, null), TestContext.Current.CancellationToken);
        Assert.Equal(HttpMethod.Get, handler.LastRequest!.Method);
        Assert.Contains("operationName=TestOp", handler.LastRequest.RequestUri!.Query);
        Assert.Contains("query=", handler.LastRequest.RequestUri.Query);
    }

    [Fact]
    public async Task ExecuteBatchAsync_Sends_Array_Payload()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""[{"data":null},{"data":null}]"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var operation = new DummyOperation(true, null);
        _ = await client.ExecuteBatchAsync(new global::Salep.Samples.MinimalDependencies.Client.IGraphQLOperation<DummyResponse, DummyVariables>[] { operation, operation }, TestContext.Current.CancellationToken);
        using var document = JsonDocument.Parse(handler.ContentText!);
        Assert.Equal(JsonValueKind.Array, document.RootElement.ValueKind);
        Assert.Equal(2, document.RootElement.GetArrayLength());
    }

    [Fact]
    public async Task ExecuteIncrementalAsync_Parses_Multipart_Response()
    {
        const string boundary = "boundary123";
        var body = string.Join("\r\n", "--" + boundary, "Content-Type: application/json", string.Empty, """{"data":null}""", "--" + boundary, "Content-Type: application/json", string.Empty, """{"data":null}""", "--" + boundary + "--");
        var response = new HttpResponseMessage(System.Net.HttpStatusCode.OK) { Content = new StringContent(body, Encoding.UTF8) };
        response.Content.Headers.ContentType = new MediaTypeHeaderValue("multipart/mixed");
        response.Content.Headers.ContentType.Parameters.Add(new NameValueHeaderValue("boundary", boundary));
        using var handler = new TestHttpMessageHandler(_ => response);
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var results = new List<GraphQLResponse<DummyResponse>>();
        await foreach (var item in client.ExecuteIncrementalAsync(new DummyOperation(true, null), TestContext.Current.CancellationToken)) results.Add(item);
        Assert.Equal(2, results.Count);
    }
    [Fact]
    public async Task ExecuteAsync_Preserves_GraphQL_Errors()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"errors":[{"message":"fixture error"}],"data":null}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.test/graphql"));
        var response = await client.ExecuteAsync(new DummyOperation(false, null), TestContext.Current.CancellationToken);
        Assert.Equal("fixture error", Assert.Single(response.Errors!).Message);
    }
    [Fact]
    public void GraphQLError_Defaults_Message()
    {
        var error = new GraphQLError();
        Assert.Equal(string.Empty, error.Message);
        var response = new GraphQLResponse<DummyResponse> { Errors = new[] { error } };
        Assert.NotNull(response.Errors);
    }

    [Fact]
    public void GraphQLError_Deserializes_Details()
    {
        var response = ReadResponse<DummyResponse>("""{"errors":[{"message":"bad","locations":[{"line":2,"column":4}],"path":["users",0,"name"],"extensions":{"code":"BAD"}}]}""");
        var error = Assert.Single(response.Errors!);
        Assert.Equal("bad", error.Message);
        Assert.Equal(2, error.Locations![0].Line);
        Assert.Equal(4, error.Locations[0].Column);
        Assert.Equal("users", error.Path![0].GetString());
        Assert.Equal(0, error.Path[1].GetInt32());
        Assert.Equal("name", error.Path[2].GetString());
        Assert.Equal("BAD", error.Extensions!.Value.GetProperty("code").GetString());
    }
    [Fact]
    public void GraphQLResponse_Allows_Null_List_Items()
    {
        var response = ReadResponse<DummyListResponse>("""{"data":{"posts":[null]}}""");
        Assert.Single(response.Data!.Posts!);
        Assert.Null(response.Data!.Posts![0]);
    }

    [Fact]
    public void GraphQLResponse_Allows_Null_For_NonNull_Field_With_Errors()
    {
        var response = ReadResponse<DummyUsersResponse>("""{"data":{"users":null},"errors":[{"message":"Non-null violation"}]}""");
        Assert.NotEmpty(response.Errors!);
        Assert.NotNull(response.Data);
        Assert.Null(response.Data.Users);
    }

    [Fact]
    public void GraphQLResponse_Allows_Null_Data_With_Errors()
    {
        var response = ReadResponse<DummyUsersResponse>("""{"data":null,"errors":[{"message":"Failure"}]}""");
        Assert.NotEmpty(response.Errors!);
        Assert.Null(response.Data);
    }
    private static GraphQLResponse<T> ReadResponse<T>(string json)
        => JsonSerializer.Deserialize<GraphQLResponse<T>>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;
}
