<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NodaTime" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3.mtp-v2" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Salep.ClientGenerator" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Salep.Samples.Opinionated.Module\Salep.Samples.Opinionated.Module.csproj" />
    </ItemGroup>

</Project>