<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SalepConfigFile>salep.json</SalepConfigFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dunet" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
    <ProjectReference Include="../Client/Salep.Samples.Opinionated.Client.csproj" />
    <PackageReference Include="Salep.ClientGenerator" PrivateAssets="all" />
  </ItemGroup>
</Project>
