using Salep.ClientGenerator.Config;

namespace Salep.ClientGenerator.Emission;

internal static class AgentInstructionsEmitter
{
    public static string GenerateClientInstructions(GeneratorConfig config)
    {
        var clientClass = string.IsNullOrWhiteSpace(config.ClientClassName) ? "GraphQLClient" : config.ClientClassName;
        var unionInstructions = config.UseNativeUnions
            ? "2. **Discriminated Unions (C# 15)**:\n   - GraphQL unions and interfaces are emitted as native C# 15 union declarations.\n   - Use exhaustive type-pattern `switch` expressions to handle each case."
            : "2. **Discriminated Unions (Dunet)**:\n   - GraphQL unions and interfaces are generated as compile-time safe discriminated unions using **Dunet** (`[Union]`).\n   - **Never** use direct type-casting (e.g. `(MyType)result`) or `is` pattern checks.\n   - **Always** use the exhaustive `.Match(...)` extension method to handle union variants.";

        return $$"""
# AI Agent Directives — Generated GraphQL Client

> **NOTICE FOR AI AGENTS & DEVELOPERS**:
> This directory contains **auto-generated build artifacts** produced by **Salep**.
> **STRICTLY DO NOT MANUALLY EDIT, FORMAT, RENAME, OR DELETE ANY FILES IN THIS DIRECTORY.**
> Any manual changes will be overwritten and lost on the next build.

---

### How to Modify This Code

To alter the generated types or client behaviors, always modify upstream sources:

1. **Schema & Types**: Edit the GraphQL SDL schema file (e.g. `schema.graphql`).
2. **Operations & Queries**: Edit or add `.graphql` files in the configured operations directory.
3. **Configuration**: Edit `salep.json` (for namespaces, client name, scalar mappings, NodaTime, transport options).
4. **Regenerate**: Run `dotnet build` (or execute `dotnet run --project .../Salep.ClientGenerator.Cli.csproj -- --config salep.json`).

---

### Consumption Rules for AI Agents

When consuming or referencing this generated client in application code, adhere to these invariants:

1. **Read-Only API Discovery**:
   - Treat generated files as a strongly-typed, read-only contract.
   - Inspect the generated client class and operation models to discover available methods, parameter inputs, and response payloads.
   - Specific operation contracts and models are self-documenting in the generated C# code.

{{unionInstructions}}

3. **Dependency Injection**:
   - Register the generated client with `IHttpClientFactory` in `Program.cs` / `IServiceCollection`:
     ```csharp
     builder.Services.AddHttpClient("graphql");
     builder.Services.AddTransient(provider => new {{clientClass}}(
         provider.GetRequiredService<IHttpClientFactory>().CreateClient("graphql"),
         new Uri("https://api.example.com/graphql")));
     ```

4. **GraphQL Error Handling**:
   - Always check `response.Errors` before accessing `response.Data`.
   - GraphQL allows partial responses where `Data` may be partially populated alongside error messages.

5. **Multi-Project Deduplication**:
   - In solutions utilizing explicit client references (`"baseClient"` in a version 1 client configuration), symbol ownership is tracked in `.salep.manifest.json`.
   - Build referenced client projects first; missing or stale contracts are errors. Profiles share defaults and never establish symbol ownership.
   - Types defined and generated by ancestor projects are automatically suppressed in downstream modules to prevent duplicate C# symbol definitions (`CS0433`).
""";
    }

    public static string GenerateTestInstructions(GeneratorConfig config)
    {
        var clientClass = string.IsNullOrWhiteSpace(config.ClientClassName) ? "GraphQLClient" : config.ClientClassName;

        return $$"""
# AI Agent Directives — Generated GraphQL Test Suite

> **NOTICE FOR AI AGENTS & DEVELOPERS**:
> This directory contains **auto-generated test artifacts** produced by **Salep**.
> **STRICTLY DO NOT MANUALLY EDIT, FORMAT, RENAME, OR DELETE ANY FILES IN THIS DIRECTORY.**
> Any manual changes will be overwritten and lost on the next build.

---

### Authoritative Client Contract

This configuration has `kind: "tests"` and references a concrete `client`. Union representation, scalars, operation signatures, and transport behavior come exclusively from its verified manifest. Change those settings in the client or its profile, then rebuild the client before generating tests. NuGet references remain developer-owned.

### Purpose of Generated Tests

The test suite in this directory provides automated verification for:
- Operation metadata (operation names, document hashes, variable schemas).
- JSON payload serialization and GraphQL-over-HTTP transport protocol compliance.
- Response deserialization, nullability handling, and custom scalar conversions.
- Polymorphic union deserialization via `__typename` discriminant mapping.

---

### In-Memory Mock Testing with `TestHttpMessageHandler`

When writing application-level unit tests for components that consume the GraphQL client:
- Do not spin up an external HTTP server or mock client methods directly.
- Use the generated `TestHttpMessageHandler` to return mock responses:
  ```csharp
  var handler = new TestHttpMessageHandler(_ =>
      TestHttpMessageHandler.JsonResponse("{\"data\":null}"));
  var httpClient = new HttpClient(handler);
  var client = new {{clientClass}}(httpClient, new Uri("http://localhost/graphql"));
  ```
""";
    }
}
