using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Salep.ClientGenerator.Config;

namespace Salep.ClientGenerator.Emission;

internal static class RoslynEmitter
{
    public static CSharpParseOptions GetParseOptions(GeneratorConfig config)
        => new(config.UseNativeUnions ? LanguageVersion.Preview : LanguageVersion.CSharp14);

    public static string EmitFile(GeneratorConfig config, string namespaceName, IEnumerable<string> usings, IEnumerable<MemberDeclarationSyntax> members)
        => "// <auto-generated/>\n#nullable enable\n" + Emit(config, namespaceName, usings, members) + "\n";

    public static string Emit(GeneratorConfig config, string namespaceName, IEnumerable<string> usings, IEnumerable<MemberDeclarationSyntax> members)
    {
        var root = SyntaxFactory.CompilationUnit()
            .WithUsings(SyntaxFactory.List(usings.Append(config.SharedNamespace).Distinct(StringComparer.Ordinal).Where(item => !string.IsNullOrWhiteSpace(item)).Select(item => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(item)))))
            .WithMembers(SyntaxFactory.SingletonList<MemberDeclarationSyntax>(SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.ParseName(namespaceName))
                .WithMembers(SyntaxFactory.List(members))));
        root = root.AddUsings(config.TypeOwners.OrderBy(pair => pair.Key, StringComparer.Ordinal).Where(pair => pair.Value != namespaceName).Select(pair =>
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("global::" + pair.Value + "." + pair.Key)).WithAlias(SyntaxFactory.NameEquals(pair.Key))).ToArray());
        ThrowOnErrors(root.GetDiagnostics(), namespaceName);
        var output = root.NormalizeWhitespace(indentation: new string(' ', config.IndentSize), eol: "\n").ToFullString();
        ThrowOnErrors(CSharpSyntaxTree.ParseText(output, GetParseOptions(config)).GetDiagnostics(), namespaceName);
        return output;
    }

    private static void ThrowOnErrors(IEnumerable<Diagnostic> diagnostics, string namespaceName)
    {
        var errors = diagnostics.Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        if (errors.Length > 0)
        {
            throw new InvalidOperationException($"Invalid generated C# in namespace '{namespaceName}':{Environment.NewLine}"
                + string.Join(Environment.NewLine, errors.Select(error => error.ToString())));
        }
    }
}
