using System.Text.Json;
using Salep.ClientGenerator.Generation;
using Salep.ClientGenerator.Model;
using Salep.ClientGenerator.Targets;
using Salep.ClientGenerator.Templates;
using Salep.GraphQLParser;
using Scriban.Runtime;
using Scriban.Syntax;
using Xunit;

namespace Salep.ClientGenerator.Tests;

public sealed class TemplateCompositionTests
{
    [Fact]
    public void Fragments_receive_current_type_field_operation_and_transport_models()
    {
        var schema = GraphQlModelFactory.CreateSchema(Parse("input Filter { name: String! } type Query { hello(filter: Filter!): String! }"));
        var operations = GraphQlModelFactory.CreateExecutable(schema, [Parse("query Hello($filter: Filter!) { hello(filter: $filter) }")]);
        var overrides = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [ScribanTemplateNames.SchemaObjectMembers] = "    public string SchemaName => {{ target.string_literal type.name }};\n",
            [ScribanTemplateNames.SchemaInputProperty] = "    // input property {{ field.name }}\n" + ScribanTemplateCatalog.ReadDefault(ScribanTemplateNames.SchemaInputProperty),
            [ScribanTemplateNames.OperationsContractMembers] = "    public string ContractName => {{ target.string_literal operation.name }};\n",
            [ScribanTemplateNames.OperationsResponseObjectProperty] = "    // response property {{ field.property_name }}\n" + ScribanTemplateCatalog.ReadDefault(ScribanTemplateNames.OperationsResponseObjectProperty),
            [ScribanTemplateNames.ClientConstructorBody] = "        _httpClient.DefaultRequestHeaders.Add(\"X-Client\", {{ target.string_literal settings.client_name }});\n",
            [ScribanTemplateNames.ClientAfterResponse] = "        // after-response hook\n",
            [ScribanTemplateNames.ClientMembers] = "    public string ConsumerName => {{ target.string_literal settings.client_name }};\n"
        };
        var files = new ScribanCSharpTemplateGenerator().GenerateClientSources(schema, operations,
            new CSharpCodeGenerationTarget(), templateOverrides: overrides).ToDictionary(file => file.FileName, file => file.Content);
        Assert.Contains("SchemaName => \"Query\"", files["SchemaTypes.cs"], StringComparison.Ordinal);
        Assert.Contains("// input property name", files["SchemaTypes.cs"], StringComparison.Ordinal);
        Assert.Contains("ContractName => \"Hello\"", files["Operations.cs"], StringComparison.Ordinal);
        Assert.Contains("// response property Hello", files["Operations.cs"], StringComparison.Ordinal);
        Assert.Contains("ConsumerName => \"GraphQLClient\"", files["GraphQLClient.cs"], StringComparison.Ordinal);
        Assert.Contains("DefaultRequestHeaders.Add(\"X-Client\", \"GraphQLClient\")", files["GraphQLClient.cs"], StringComparison.Ordinal);
        Assert.Equal(3, files["GraphQLClient.cs"].Split("// after-response hook", StringSplitOptions.None).Length - 1);
        Assert.Contains("ExecuteIncrementalAsync", files["GraphQLClient.cs"], StringComparison.Ordinal);
        Assert.StartsWith("// <auto-generated/>", files["GraphQLClient.cs"], StringComparison.Ordinal);
    }

    [Fact]
    public void Whole_file_overrides_can_compose_defaults_and_overridden_fragments()
    {
        var overrides = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [ScribanTemplateNames.ClientMembers] = "public string Marker => \"consumer\";\n"
        };
        overrides[ScribanTemplateNames.Client] = "// custom wrapper\n{{ include \"default:client\" }}";
        var source = new ScribanCSharpTemplateGenerator().GenerateClient(new CSharpCodeGenerationTarget(),
            templateOverrides: overrides);
        Assert.StartsWith("// custom wrapper", source, StringComparison.Ordinal);
        Assert.Contains("Marker => \"consumer\"", source, StringComparison.Ordinal);
        Assert.Contains("ReadResponseAsync", source, StringComparison.Ordinal);
        Assert.DoesNotContain("<auto-generated/>", source, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("../../outside.scriban")]
    [InlineData("not-a-template")]
    public void Includes_reject_unknown_keys_and_filesystem_paths(string name)
    {
        var error = Assert.Throws<ScriptRuntimeException>(() => new ScribanTemplateEngine().Render(
            "{{ include name }}", new ScriptObject { ["name"] = name }, "consumer.scriban"));
        Assert.Contains(name, error.Message, StringComparison.Ordinal);
        Assert.Contains("consumer.scriban", error.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("{{ if }}", "parsing")]
    [InlineData("{{ missing }}", "missing")]
    public void Broken_fragments_report_the_named_source(string source, string expected)
    {
        var error = Assert.ThrowsAny<ScriptRuntimeException>(() => new ScribanTemplateEngine().Render(
            "{{ include \"client.members\" }}", new ScriptObject(), templateOverrides: new Dictionary<string, string>
            { [ScribanTemplateNames.ClientMembers] = source }));
        Assert.Contains("client.members", error.Message, StringComparison.Ordinal);
        Assert.Contains(expected, error.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Recursive_includes_and_fragment_loops_use_engine_limits()
    {
        var engine = new ScribanTemplateEngine(new() { RecursiveLimit = 8, LoopLimit = 4 });
        var overrides = new Dictionary<string, string>
        { [ScribanTemplateNames.ClientMembers] = "{{ include \"client.annotations\" }}", [ScribanTemplateNames.ClientAnnotations] = "{{ include \"client.members\" }}" };
        Assert.Throws<ScriptRuntimeException>(() => engine.Render("{{ include \"client.members\" }}", new ScriptObject(), templateOverrides: overrides));
        overrides[ScribanTemplateNames.ClientMembers] = "{{ for i in 1..20 }}{{ i }}{{ end }}";
        Assert.Throws<ScriptRuntimeException>(() => engine.Render("{{ include \"client.members\" }}", new ScriptObject(), templateOverrides: overrides));
    }

    [Fact]
    public void Profile_fragment_paths_inherit_and_local_entries_override_without_replacing_other_fragments()
    {
        var root = Path.Combine(Path.GetTempPath(), "salep-fragments-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Path.Combine(root, "profile"));
        try
        {
            File.WriteAllText(Path.Combine(root, "schema.graphql"), "type Query { hello: String! }");
            File.WriteAllText(Path.Combine(root, "operation.graphql"), "query Hello { hello }");
            File.WriteAllText(Path.Combine(root, "profile", "members.scriban-cs"), "    // inherited {{ settings.client_name }}\n");
            File.WriteAllText(Path.Combine(root, "profile", "annotations.scriban-cs"), "// parent annotation\n");
            File.WriteAllText(Path.Combine(root, "annotations.scriban-cs"), "// child annotation\n");
            File.WriteAllText(Path.Combine(root, "profile", "base.json"), """
                {"version":1,"kind":"profile","templates":{"client.members":"members.scriban-cs","client.annotations":"annotations.scriban-cs"}}
                """);
            File.WriteAllText(Path.Combine(root, "salep.json"), """
                {"version":1,"kind":"client","profile":"profile/base.json","schema":"schema.graphql","operations":"operation.graphql","output":"Generated","templates":{"client.annotations":"annotations.scriban-cs"}}
                """);
            ScribanGenerator.Generate(new("salep.json", root));
            var source = File.ReadAllText(Path.Combine(root, "Generated", "GraphQLClient.cs"));
            Assert.Contains("// inherited GraphQLClient", source, StringComparison.Ordinal);
            Assert.Contains("// child annotation", source, StringComparison.Ordinal);
            Assert.DoesNotContain("// parent annotation", source, StringComparison.Ordinal);
            var inputs = ScribanGenerator.GetInputFiles(new("salep.json", root));
            Assert.Contains(GeneratorPathPolicy.Normalize(Path.Combine(root, "profile", "members.scriban-cs")), inputs);
            Assert.Contains(GeneratorPathPolicy.Normalize(Path.Combine(root, "annotations.scriban-cs")), inputs);
            using var manifest = JsonDocument.Parse(File.ReadAllText(Path.Combine(root, "Generated", ".salep.manifest.json")));
            Assert.True(manifest.RootElement.GetProperty("Inputs").TryGetProperty("../profile/members.scriban-cs", out _));
        }
        finally { Directory.Delete(root, true); }
    }

    [Fact]
    public void Export_contains_all_fragment_defaults_including_empty_hooks()
    {
        var root = Path.Combine(Path.GetTempPath(), "salep-template-export-" + Guid.NewGuid().ToString("N"));
        try
        {
            var exported = ScribanTemplateCatalog.WriteDefaults(root);
            Assert.Equal(ScribanTemplateCatalog.GetDefaultTemplateFiles().Count, exported.Count);
            Assert.Contains(exported, file => Path.GetFileName(file) == "CSharpClientReadResponse.scriban-cs");
            Assert.Equal("", File.ReadAllText(Path.Combine(root, "CSharpClientMembers.scriban-cs")));
        }
        finally { Directory.Delete(root, true); }
    }

    [Fact]
    public void Fragment_errors_are_configuration_diagnostics_and_do_not_publish_partial_output()
    {
        var root = Path.Combine(Path.GetTempPath(), "salep-fragment-error-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            File.WriteAllText(Path.Combine(root, "schema.graphql"), "type Query { hello: String! }");
            File.WriteAllText(Path.Combine(root, "operation.graphql"), "query Hello { hello }");
            File.WriteAllText(Path.Combine(root, "members.scriban-cs"), "// valid hook\n");
            File.WriteAllText(Path.Combine(root, "salep.json"), """
                {"version":1,"kind":"client","schema":"schema.graphql","operations":"operation.graphql","output":"Generated","templates":{"client.members":"members.scriban-cs"}}
                """);
            ScribanGenerator.Generate(new("salep.json", root));
            var previous = Directory.GetFiles(Path.Combine(root, "Generated")).ToDictionary(file => Path.GetFileName(file)!, File.ReadAllText);
            File.WriteAllText(Path.Combine(root, "members.scriban-cs"), "{{ if }}");
            var error = Assert.Throws<ScribanConfigurationException>(() => ScribanGenerator.Generate(new("salep.json", root)));
            Assert.Equal("SALEPS1006", error.Diagnostic.Code);
            Assert.Contains("client.members", error.Diagnostic.Message, StringComparison.Ordinal);
            foreach (var file in previous) Assert.Equal(file.Value, File.ReadAllText(Path.Combine(root, "Generated", file.Key!)));
        }
        finally { Directory.Delete(root, true); }
    }

    [Fact]
    public void Export_keys_and_configuration_schema_stay_synchronized()
    {
        var catalogKeys = ScribanTemplateCatalog.GetDefaultTemplateFiles().Keys.Order(StringComparer.Ordinal).ToArray();
        var apiKeys = typeof(ScribanTemplateNames).GetFields(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static)
            .Select(field => (string)field.GetRawConstantValue()!).Order(StringComparer.Ordinal).ToArray();
        Assert.Equal(apiKeys, catalogKeys);
        var root = new DirectoryInfo(AppContext.BaseDirectory);
        while (root is not null && !File.Exists(Path.Combine(root.FullName, "Directory.Build.props"))) root = root.Parent;
        Assert.NotNull(root);
        using var schema = JsonDocument.Parse(File.ReadAllText(Path.Combine(root.FullName, "docs", "client-generator", "config.schema.json")));
        foreach (var kind in schema.RootElement.GetProperty("oneOf").EnumerateArray())
        {
            var keys = kind.GetProperty("properties").GetProperty("templates").GetProperty("propertyNames").GetProperty("enum")
                .EnumerateArray().Select(value => value.GetString()!).Order(StringComparer.Ordinal).ToArray();
            Assert.Equal(catalogKeys, keys);
        }
    }

    [Fact]
    public void Included_override_content_does_not_leak_between_renders()
    {
        var engine = new ScribanTemplateEngine();
        var model = new ScriptObject();
        var overrides = new Dictionary<string, string> { [ScribanTemplateNames.ClientMembers] = "first" };
        Assert.Equal("first", engine.Render("{{ include \"client.members\" }}", model, templateOverrides: overrides));
        overrides[ScribanTemplateNames.ClientMembers] = "second";
        Assert.Equal("second", engine.Render("{{ include \"client.members\" }}", model, templateOverrides: overrides));
        Assert.Equal("", engine.Render("{{ include \"client.members\" }}", model));
    }

    private static DocumentNode Parse(string source) => global::Salep.GraphQLParser.GraphQLParser.Parse(new SourceText(source.AsMemory()));
}
