// <auto-generated/>
#nullable enable
using GraphQL.Sharp.Generated.Module;
using Shouldly;
using Xunit;
using GraphQL.Sharp.Generated;
using AccountResult = global::GraphQL.Sharp.Generated.AccountResult;
using Comment = global::GraphQL.Sharp.Generated.Comment;
using CreatePostInput = global::GraphQL.Sharp.Generated.CreatePostInput;
using IAccount = global::GraphQL.Sharp.Generated.IAccount;
using INamed = global::GraphQL.Sharp.Generated.INamed;
using INode = global::GraphQL.Sharp.Generated.INode;
using ITimestamped = global::GraphQL.Sharp.Generated.ITimestamped;
using MetadataInput = global::GraphQL.Sharp.Generated.MetadataInput;
using Mutation = global::GraphQL.Sharp.Generated.Mutation;
using NamedResult = global::GraphQL.Sharp.Generated.NamedResult;
using NodeResult = global::GraphQL.Sharp.Generated.NodeResult;
using Post = global::GraphQL.Sharp.Generated.Post;
using Query = global::GraphQL.Sharp.Generated.Query;
using Role = global::GraphQL.Sharp.Generated.Role;
using SearchInput = global::GraphQL.Sharp.Generated.SearchInput;
using SearchResult = global::GraphQL.Sharp.Generated.SearchResult;
using Subscription = global::GraphQL.Sharp.Generated.Subscription;
using TimestampedResult = global::GraphQL.Sharp.Generated.TimestampedResult;
using User = global::GraphQL.Sharp.Generated.User;
using UserFilter = global::GraphQL.Sharp.Generated.UserFilter;

namespace Salep.Samples.Opinionated.Module.Tests;
public sealed class OperationsMetadataTests
{
    [Fact]
    public void ModuleCreatePost_Operation_Metadata()
    {
        var variables = new ModuleCreatePostVariables();
        var response = new ModuleCreatePostResponse();
        var operation = new ModuleCreatePostOperation(variables);
        operation.OperationName.ShouldBe("ModuleCreatePost");
        operation.Query.ShouldContain("ModuleCreatePost");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void ModuleUsers_Operation_Metadata()
    {
        var variables = new ModuleUsersVariables();
        var response = new ModuleUsersResponse();
        var operation = new ModuleUsersOperation(variables);
        operation.OperationName.ShouldBe("ModuleUsers");
        operation.Query.ShouldContain("ModuleUsers");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void ModulePostCreated_Operation_Metadata()
    {
        var variables = new ModulePostCreatedVariables();
        var response = new ModulePostCreatedResponse();
        var operation = new ModulePostCreatedOperation(variables);
        operation.OperationName.ShouldBe("ModulePostCreated");
        operation.Query.ShouldContain("ModulePostCreated");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }
}
