// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using GraphQL.Sharp.Generated.Module;
using Shouldly;
using Xunit;
using GraphQL.Sharp.Generated;
using AccountResult = global::GraphQL.Sharp.Generated.AccountResult;
using Comment = global::GraphQL.Sharp.Generated.Comment;
using CreatePostInput = global::GraphQL.Sharp.Generated.CreatePostInput;
using IAccount = global::GraphQL.Sharp.Generated.IAccount;
using INamed = global::GraphQL.Sharp.Generated.INamed;
using INode = global::GraphQL.Sharp.Generated.INode;
using ITimestamped = global::GraphQL.Sharp.Generated.ITimestamped;
using MetadataInput = global::GraphQL.Sharp.Generated.MetadataInput;
using Mutation = global::GraphQL.Sharp.Generated.Mutation;
using NamedResult = global::GraphQL.Sharp.Generated.NamedResult;
using NodeResult = global::GraphQL.Sharp.Generated.NodeResult;
using Post = global::GraphQL.Sharp.Generated.Post;
using Query = global::GraphQL.Sharp.Generated.Query;
using Role = global::GraphQL.Sharp.Generated.Role;
using SearchInput = global::GraphQL.Sharp.Generated.SearchInput;
using SearchResult = global::GraphQL.Sharp.Generated.SearchResult;
using Subscription = global::GraphQL.Sharp.Generated.Subscription;
using TimestampedResult = global::GraphQL.Sharp.Generated.TimestampedResult;
using User = global::GraphQL.Sharp.Generated.User;
using UserFilter = global::GraphQL.Sharp.Generated.UserFilter;

namespace Salep.Samples.Opinionated.Module.Tests;
public sealed class OperationsResponseTests
{
    [Fact]
    public async Task ModuleCreatePost_Deserializes_Response()
    {
        var json = WrapData("""
{
  "createPost": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.ModuleCreatePostAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task ModuleUsers_Deserializes_Response()
    {
        var json = WrapData("""
{
  "users": [
    {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.ModuleUsersAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task ModulePostCreated_Deserializes_Response()
    {
        var json = WrapData("""
{
  "postCreated": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.ModulePostCreatedAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    private static async Task<GraphQLResponse<TResponse>> ExecuteOperationAsync<TResponse>(Func<IGeneratedModuleOperations, Task<GraphQLResponse<TResponse>>> call, string json)
    {
        var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse(json));
        var httpClient = new HttpClient(handler);
        var client = new GeneratedModuleClient(httpClient, new Uri("https://example.com/graphql"));
        var api = new GeneratedModuleOperations(client);
        var response = await call(api);
        response.ShouldNotBeNull();
        return response;
    }

    private static string WrapData(string dataJson)
    {
        return "{\"data\":" + dataJson + "}";
    }
}
