// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using GraphQL.Sharp.Generated.Module;
using Shouldly;
using Xunit;
using NodaTime;
using NodaTime.Serialization.SystemTextJson;
using GraphQL.Sharp.Generated;
using AccountResult = global::GraphQL.Sharp.Generated.AccountResult;
using Comment = global::GraphQL.Sharp.Generated.Comment;
using CreatePostInput = global::GraphQL.Sharp.Generated.CreatePostInput;
using IAccount = global::GraphQL.Sharp.Generated.IAccount;
using INamed = global::GraphQL.Sharp.Generated.INamed;
using INode = global::GraphQL.Sharp.Generated.INode;
using ITimestamped = global::GraphQL.Sharp.Generated.ITimestamped;
using MetadataInput = global::GraphQL.Sharp.Generated.MetadataInput;
using Mutation = global::GraphQL.Sharp.Generated.Mutation;
using NamedResult = global::GraphQL.Sharp.Generated.NamedResult;
using NodeResult = global::GraphQL.Sharp.Generated.NodeResult;
using Post = global::GraphQL.Sharp.Generated.Post;
using Query = global::GraphQL.Sharp.Generated.Query;
using Role = global::GraphQL.Sharp.Generated.Role;
using SearchInput = global::GraphQL.Sharp.Generated.SearchInput;
using SearchResult = global::GraphQL.Sharp.Generated.SearchResult;
using Subscription = global::GraphQL.Sharp.Generated.Subscription;
using TimestampedResult = global::GraphQL.Sharp.Generated.TimestampedResult;
using User = global::GraphQL.Sharp.Generated.User;
using UserFilter = global::GraphQL.Sharp.Generated.UserFilter;

namespace Salep.Samples.Opinionated.Module.Tests;
public sealed class UnionConverterTests
{
    [Fact]
    public void SearchResult_Deserializes_User()
    {
        var sample = new User
        {
            Name = "sample",
            Email = "sample",
            Id = "sample",
            Role = Role.GUEST,
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Posts = new List<Post>
            {
                new Post
                {
                    Id = "sample",
                    Title = "sample",
                    CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                    Author = default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "User";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<SearchResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<SearchResult.User>();
    }

    [Fact]
    public void SearchResult_Deserializes_Post()
    {
        var sample = new Post
        {
            Id = "sample",
            Title = "sample",
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Author = new User
            {
                Name = "sample",
                Email = "sample",
                Id = "sample",
                Role = Role.GUEST,
                CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                Posts = new List<Post>
                {
                    default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "Post";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<SearchResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<SearchResult.Post>();
    }

    [Fact]
    public void SearchResult_Deserializes_Comment()
    {
        var sample = new Comment
        {
            Id = "sample",
            Body = "sample",
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Author = new User
            {
                Name = "sample",
                Email = "sample",
                Id = "sample",
                Role = Role.GUEST,
                CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                Posts = new List<Post>
                {
                    new Post
                    {
                        Id = "sample",
                        Title = "sample",
                        CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                        Author = default!
                    }
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "Comment";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<SearchResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<SearchResult.Comment>();
    }

    [Fact]
    public void SearchResult_Write_Serializes_User()
    {
        var value = new SearchResult.User(new User { Name = "sample", Email = "sample", Id = "sample", Role = Role.GUEST, CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Posts = new List<Post> { new Post { Id = "sample", Title = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = default! } } });
        var options = CreateJsonOptions();
        var json = JsonSerializer.Serialize<SearchResult>(value, options);
        json.ShouldNotBeNullOrWhiteSpace();
    }

    [Fact]
    public void SearchResult_Read_Returns_Null_When_Json_Null()
    {
        var options = CreateJsonOptions();
        var result = JsonSerializer.Deserialize<SearchResult?>("null", options);
        result.ShouldBeNull();
    }

    [Fact]
    public void SearchResult_Read_Throws_When_Typename_Missing()
    {
        var options = CreateJsonOptions();
        var json = "{\"id\":\"sample\"}";
        Should.Throw<JsonException>(() => JsonSerializer.Deserialize<SearchResult>(json, options));
    }

    [Fact]
    public void SearchResult_Read_Throws_When_Typename_Unknown()
    {
        var options = CreateJsonOptions();
        var json = "{\"__typename\":\"Unknown\"}";
        Should.Throw<JsonException>(() => JsonSerializer.Deserialize<SearchResult>(json, options));
    }

    [Fact]
    public void AccountResult_Deserializes_User()
    {
        var sample = new User
        {
            Name = "sample",
            Email = "sample",
            Id = "sample",
            Role = Role.GUEST,
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Posts = new List<Post>
            {
                new Post
                {
                    Id = "sample",
                    Title = "sample",
                    CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                    Author = default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "User";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<AccountResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<AccountResult.User>();
    }

    [Fact]
    public void AccountResult_Write_Serializes_User()
    {
        var value = new AccountResult.User(new User { Name = "sample", Email = "sample", Id = "sample", Role = Role.GUEST, CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Posts = new List<Post> { new Post { Id = "sample", Title = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = default! } } });
        var options = CreateJsonOptions();
        var json = JsonSerializer.Serialize<AccountResult>(value, options);
        json.ShouldNotBeNullOrWhiteSpace();
    }

    [Fact]
    public void NamedResult_Deserializes_User()
    {
        var sample = new User
        {
            Name = "sample",
            Email = "sample",
            Id = "sample",
            Role = Role.GUEST,
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Posts = new List<Post>
            {
                new Post
                {
                    Id = "sample",
                    Title = "sample",
                    CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                    Author = default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "User";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<NamedResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<NamedResult.User>();
    }

    [Fact]
    public void NamedResult_Write_Serializes_User()
    {
        var value = new NamedResult.User(new User { Name = "sample", Email = "sample", Id = "sample", Role = Role.GUEST, CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Posts = new List<Post> { new Post { Id = "sample", Title = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = default! } } });
        var options = CreateJsonOptions();
        var json = JsonSerializer.Serialize<NamedResult>(value, options);
        json.ShouldNotBeNullOrWhiteSpace();
    }

    [Fact]
    public void NodeResult_Deserializes_Comment()
    {
        var sample = new Comment
        {
            Id = "sample",
            Body = "sample",
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Author = new User
            {
                Name = "sample",
                Email = "sample",
                Id = "sample",
                Role = Role.GUEST,
                CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                Posts = new List<Post>
                {
                    new Post
                    {
                        Id = "sample",
                        Title = "sample",
                        CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                        Author = default!
                    }
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "Comment";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<NodeResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<NodeResult.Comment>();
    }

    [Fact]
    public void NodeResult_Deserializes_Post()
    {
        var sample = new Post
        {
            Id = "sample",
            Title = "sample",
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Author = new User
            {
                Name = "sample",
                Email = "sample",
                Id = "sample",
                Role = Role.GUEST,
                CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                Posts = new List<Post>
                {
                    default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "Post";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<NodeResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<NodeResult.Post>();
    }

    [Fact]
    public void NodeResult_Deserializes_User()
    {
        var sample = new User
        {
            Name = "sample",
            Email = "sample",
            Id = "sample",
            Role = Role.GUEST,
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Posts = new List<Post>
            {
                new Post
                {
                    Id = "sample",
                    Title = "sample",
                    CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                    Author = default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "User";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<NodeResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<NodeResult.User>();
    }

    [Fact]
    public void NodeResult_Write_Serializes_Comment()
    {
        var value = new NodeResult.Comment(new Comment { Id = "sample", Body = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = new User { Name = "sample", Email = "sample", Id = "sample", Role = Role.GUEST, CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Posts = new List<Post> { new Post { Id = "sample", Title = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = default! } } } });
        var options = CreateJsonOptions();
        var json = JsonSerializer.Serialize<NodeResult>(value, options);
        json.ShouldNotBeNullOrWhiteSpace();
    }

    [Fact]
    public void TimestampedResult_Deserializes_Comment()
    {
        var sample = new Comment
        {
            Id = "sample",
            Body = "sample",
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Author = new User
            {
                Name = "sample",
                Email = "sample",
                Id = "sample",
                Role = Role.GUEST,
                CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                Posts = new List<Post>
                {
                    new Post
                    {
                        Id = "sample",
                        Title = "sample",
                        CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                        Author = default!
                    }
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "Comment";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<TimestampedResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<TimestampedResult.Comment>();
    }

    [Fact]
    public void TimestampedResult_Deserializes_Post()
    {
        var sample = new Post
        {
            Id = "sample",
            Title = "sample",
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Author = new User
            {
                Name = "sample",
                Email = "sample",
                Id = "sample",
                Role = Role.GUEST,
                CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                Posts = new List<Post>
                {
                    default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "Post";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<TimestampedResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<TimestampedResult.Post>();
    }

    [Fact]
    public void TimestampedResult_Deserializes_User()
    {
        var sample = new User
        {
            Name = "sample",
            Email = "sample",
            Id = "sample",
            Role = Role.GUEST,
            CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
            Posts = new List<Post>
            {
                new Post
                {
                    Id = "sample",
                    Title = "sample",
                    CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0),
                    Author = default!
                }
            }
        };
        var options = CreateJsonOptions();
        var node = JsonSerializer.SerializeToNode(sample, options)!.AsObject();
        node["__typename"] = "User";
        var json = node.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
        var result = JsonSerializer.Deserialize<TimestampedResult>(json, options);
        result.ShouldNotBeNull();
        result.ShouldBeOfType<TimestampedResult.User>();
    }

    [Fact]
    public void TimestampedResult_Write_Serializes_Comment()
    {
        var value = new TimestampedResult.Comment(new Comment { Id = "sample", Body = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = new User { Name = "sample", Email = "sample", Id = "sample", Role = Role.GUEST, CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Posts = new List<Post> { new Post { Id = "sample", Title = "sample", CreatedAt = NodaTime.Instant.FromUtc(2020, 1, 1, 0, 0), Author = default! } } } });
        var options = CreateJsonOptions();
        var json = JsonSerializer.Serialize<TimestampedResult>(value, options);
        json.ShouldNotBeNullOrWhiteSpace();
    }

    private static JsonSerializerOptions CreateJsonOptions()
    {
        var options = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true
        };
        options.Converters.Add(new JsonStringEnumConverter());
        options.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
        global::GraphQL.Sharp.Generated.UnionJsonConverters.Register(options);
        global::GraphQL.Sharp.Generated.Module.UnionJsonConverters.Register(options);
        return options;
    }
}
