<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../IntegrationTests/GraphQLIntegrationTests.cs" Link="GraphQLIntegrationTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Alba" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="../Client/Salep.Samples.Opinionated.Scriban.Client.csproj" />
    <ProjectReference Include="../Module/Salep.Samples.Opinionated.Scriban.Module.csproj" />
    <ProjectReference Include="../../../Salep.Samples.GraphQLServer/Salep.Samples.GraphQLServer.csproj" />
  </ItemGroup>
</Project>
