// <auto-generated/>
#nullable enable
using Xunit;
using Salep.Samples.Opinionated.Client;
using Salep.Samples.Opinionated.ModuleClient;

namespace Salep.Samples.Opinionated.ModuleClient.Tests;

public sealed class OperationsMetadataTests
{
    [Fact]
    public void ModuleCreatePost_Operation_Metadata()
    {
        var variables = new ModuleCreatePostVariables();
        var response = new ModuleCreatePostResponse();
        var operation = new ModuleCreatePostOperation(variables);
        Assert.Equal("ModuleCreatePost", operation.OperationName);
        Assert.Contains("ModuleCreatePost", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void ModuleUsers_Operation_Metadata()
    {
        var variables = new ModuleUsersVariables();
        var response = new ModuleUsersResponse();
        var operation = new ModuleUsersOperation(variables);
        Assert.Equal("ModuleUsers", operation.OperationName);
        Assert.Contains("ModuleUsers", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
    [Fact]
    public void ModulePostCreated_Operation_Metadata()
    {
        var variables = new ModulePostCreatedVariables();
        var response = new ModulePostCreatedResponse();
        var operation = new ModulePostCreatedOperation(variables);
        Assert.Equal("ModulePostCreated", operation.OperationName);
        Assert.Contains("ModulePostCreated", operation.Query);
        Assert.Same(variables, operation.Variables);
        Assert.NotNull(response);
    }
}
