// <auto-generated/>
#nullable enable
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Xunit;
using Salep.Samples.Opinionated.Client;
using Salep.Samples.Opinionated.ModuleClient;
namespace Salep.Samples.Opinionated.ModuleClient.Tests;

public sealed class OperationsResponseTests
{
    [Fact]
    public async Task ModuleCreatePost_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"createPost":{"id":"sample","title":"sample"}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLModuleClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLModuleOperations(client);
        var response = await api.ModuleCreatePostAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task ModuleUsers_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"users":[{"id":"sample","name":"sample","role":"GUEST"}]}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLModuleClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLModuleOperations(client);
        var response = await api.ModuleUsersAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
    [Fact]
    public async Task ModulePostCreated_Deserializes_Response()
    {
        using var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""{"data":{"postCreated":{"id":"sample","title":"sample"}}}"""));
        using var httpClient = new HttpClient(handler);
        var client = new GraphQLModuleClient(httpClient, new Uri("https://example.test/graphql"));
        var api = new GraphQLModuleOperations(client);
        var response = await api.ModulePostCreatedAsync(TestContext.Current.CancellationToken);
        Assert.NotNull(response);
        Assert.NotNull(response.Data);
    }
}
