// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using GraphQL.Sharp.Generated;
using Shouldly;
using Xunit;

namespace Salep.Samples.Opinionated.Client.Tests;
public sealed class OperationsResponseTests
{
    [Fact]
    public async Task CreatePostSimple_Deserializes_Response()
    {
        var json = WrapData("""
{
  "createPost": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.CreatePostSimpleAsync(new CreatePostSimpleVariables { Title = "sample" }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task CreatePostWithContent_Deserializes_Response()
    {
        var json = WrapData("""
{
  "createPost": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.CreatePostWithContentAsync(new CreatePostWithContentVariables { Title = "sample", Content = "sample" }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task CreatePostAliased_Deserializes_Response()
    {
        var json = WrapData("""
{
  "first": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  },
  "second": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.CreatePostAliasedAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task UpdatePostWithDefaults_Deserializes_Response()
    {
        var json = WrapData("""
{
  "updatePost": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.UpdatePostWithDefaultsAsync(new UpdatePostWithDefaultsVariables { Id = "sample", Input = new CreatePostInput { Title = "sample", Content = "sample", Tags = new List<string?> { "sample" }, Meta = new MetadataInput { Rating = 123, Flags = new List<string> { "sample" } }, Notify = true } }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task DeletePosts_Deserializes_Response()
    {
        var json = WrapData("""
{
  "deleted": [
    {
      "id": "sample",
      "title": "sample",
      "createdAt": "2020-01-01T00:00:00Z",
      "author": {
        "name": "sample",
        "email": "sample",
        "id": "sample",
        "role": "GUEST",
        "createdAt": "2020-01-01T00:00:00Z",
        "posts": [
          {
            "id": "sample",
            "title": "sample",
            "createdAt": "2020-01-01T00:00:00Z",
            "author": {
              "name": "sample",
              "email": "sample",
              "id": "sample",
              "role": "GUEST",
              "createdAt": "2020-01-01T00:00:00Z",
              "posts": []
            }
          }
        ]
      }
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.DeletePostsAsync(new DeletePostsVariables { Ids = new List<string> { "sample" } }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task UsersDefaultRole_Deserializes_Response()
    {
        var json = WrapData("""
{
  "users": [
    {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.UsersDefaultRoleAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task UsersByRole_Deserializes_Response()
    {
        var json = WrapData("""
{
  "admins": [
    {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ],
  "guests": [
    {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.UsersByRoleAsync(new UsersByRoleVariables { Role = Role.GUEST, Filter = new UserFilter { Roles = new List<Role> { Role.GUEST }, Ids = new List<string> { "sample" } } }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task SearchUsersAndPosts_Deserializes_Response()
    {
        var json = WrapData("""
{
  "search": [
    {
      "__typename": "User",
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.SearchUsersAndPostsAsync(new SearchUsersAndPostsVariables { Text = "sample" }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task NodeById_Deserializes_Response()
    {
        var json = WrapData("""
{
  "byId": {
    "__typename": "Comment",
    "id": "sample",
    "body": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.NodeByIdAsync(new NodeByIdVariables { Id = "sample" }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task SearchWithMultipleInlineFragments_Deserializes_Response()
    {
        var json = WrapData("""
{
  "results": [
    {
      "__typename": "User",
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.SearchWithMultipleInlineFragmentsAsync(new SearchWithMultipleInlineFragmentsVariables { Text = "sample" }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task EchoList_Deserializes_Response()
    {
        var json = WrapData("""
{
  "echoed": [
    "sample"
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.EchoListAsync(new EchoListVariables { Values = new List<string> { "sample" } }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task PostsByIds_Deserializes_Response()
    {
        var json = WrapData("""
{
  "posts": [
    {
      "id": "sample",
      "title": "sample",
      "createdAt": "2020-01-01T00:00:00Z",
      "author": {
        "name": "sample",
        "email": "sample",
        "id": "sample",
        "role": "GUEST",
        "createdAt": "2020-01-01T00:00:00Z",
        "posts": [
          {
            "id": "sample",
            "title": "sample",
            "createdAt": "2020-01-01T00:00:00Z",
            "author": {
              "name": "sample",
              "email": "sample",
              "id": "sample",
              "role": "GUEST",
              "createdAt": "2020-01-01T00:00:00Z",
              "posts": []
            }
          }
        ]
      }
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.PostsByIdsAsync(new PostsByIdsVariables { Ids = new List<string> { "sample" }, AllowMissing = true }, TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task UnusedVar_Deserializes_Response()
    {
        var json = WrapData("""
{
  "users": [
    {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  ]
}
""");
        var response = await ExecuteOperationAsync(api => api.UnusedVarAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task PostCreatedFull_Deserializes_Response()
    {
        var json = WrapData("""
{
  "postCreated": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.PostCreatedFullAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task PostCreatedMinimal_Deserializes_Response()
    {
        var json = WrapData("""
{
  "postCreated": {
    "id": "sample",
    "title": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.PostCreatedMinimalAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    [Fact]
    public async Task CommentAdded_Deserializes_Response()
    {
        var json = WrapData("""
{
  "commentAdded": {
    "id": "sample",
    "body": "sample",
    "createdAt": "2020-01-01T00:00:00Z",
    "author": {
      "name": "sample",
      "email": "sample",
      "id": "sample",
      "role": "GUEST",
      "createdAt": "2020-01-01T00:00:00Z",
      "posts": [
        {
          "id": "sample",
          "title": "sample",
          "createdAt": "2020-01-01T00:00:00Z",
          "author": {
            "name": "sample",
            "email": "sample",
            "id": "sample",
            "role": "GUEST",
            "createdAt": "2020-01-01T00:00:00Z",
            "posts": []
          }
        }
      ]
    }
  }
}
""");
        var response = await ExecuteOperationAsync(api => api.CommentAddedAsync(TestContext.Current.CancellationToken), json);
        response.ShouldNotBeNull();
    }

    private static async Task<GraphQLResponse<TResponse>> ExecuteOperationAsync<TResponse>(Func<IGraphQLOperations, Task<GraphQLResponse<TResponse>>> call, string json)
    {
        var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse(json));
        var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.com/graphql"));
        var api = new GraphQLOperations(client);
        var response = await call(api);
        response.ShouldNotBeNull();
        return response;
    }

    private static string WrapData(string dataJson)
    {
        return "{\"data\":" + dataJson + "}";
    }
}
