<Project>
  <PropertyGroup>
    <SalepEnabled Condition="'$(SalepEnabled)' == ''">true</SalepEnabled>
    <SalepConfigFile Condition="'$(SalepConfigFile)' == ''">salep.json</SalepConfigFile>
    <SalepToolPath Condition="'$(SalepToolPath)' == '' and Exists('$(MSBuildThisFileDirectory)../tools/$(TargetFramework)/any/Salep.ClientGenerator.Cli.dll')">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/$(TargetFramework)/any'))</SalepToolPath>
  </PropertyGroup>
</Project>
