// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;
using System.Threading.Tasks;
using GraphQL.Sharp.Generated;
using NSubstitute;
using Shouldly;
using Xunit;

namespace Salep.Samples.MinimalDependencies.Client.Tests;
public sealed class GraphQLClientPayloadTests
{
    public sealed record DummyResponse
    {
    }

    public sealed record DummyVariables(string Value);
    public sealed record DummyUser
    {
    }

    public sealed record DummyUsersResponse
    {
        public List<DummyUser>? Users { get; init; }
    }

    public sealed record DummyListResponse
    {
        public List<string?> Posts { get; init; } = new List<string?>();
    }

    [Fact]
    public async Task ExecuteAsync_SerializesOperationPayload()
    {
        var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""
{
  "data": null
}
"""));
        var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.com/graphql"));
        var operation = Substitute.For<global::GraphQL.Sharp.Generated.IGraphQLOperation<DummyResponse, DummyVariables>>();
        operation.OperationName.Returns("TestOp");
        operation.Query.Returns("mutation TestOp { __typename }");
        operation.Variables.Returns(new DummyVariables("value"));
        await client.ExecuteAsync(operation, TestContext.Current.CancellationToken);
        var payload = handler.ContentText.ShouldNotBeNull();
        using var document = JsonDocument.Parse(payload);
        document.RootElement.GetProperty("operationName").GetString()!.ShouldBe("TestOp");
        document.RootElement.GetProperty("query").GetString()!.ShouldContain("TestOp");
        document.RootElement.GetProperty("variables").GetProperty("value").GetString()!.ShouldBe("value");
    }

    [Fact]
    public async Task ExecuteAsync_Omits_Null_Variables()
    {
        var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""
{
  "data": null
}
"""));
        var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.com/graphql"));
        var operation = Substitute.For<global::GraphQL.Sharp.Generated.IGraphQLOperation<DummyResponse, DummyVariables>>();
        operation.OperationName.Returns("TestOp");
        operation.Query.Returns("mutation TestOp { __typename }");
        operation.Variables.Returns((DummyVariables? )null);
        await client.ExecuteAsync(operation, TestContext.Current.CancellationToken);
        var payload = handler.ContentText.ShouldNotBeNull();
        using var document = JsonDocument.Parse(payload);
        document.RootElement.TryGetProperty("variables", out _).ShouldBeFalse();
    }

    [Fact]
    public async Task ExecuteIncrementalAsync_Parses_Multipart_Response()
    {
        var boundary = "boundary123";
        var body = string.Join("\r\n", new[] { "--" + boundary, "Content-Type: application/json", string.Empty, "{\"data\":null}", "--" + boundary, "Content-Type: application/json", string.Empty, "{\"data\":null}", "--" + boundary + "--" });
        var response = new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent(body, Encoding.UTF8)
        };
        response.Content.Headers.ContentType = new MediaTypeHeaderValue("multipart/mixed");
        response.Content.Headers.ContentType.Parameters.Add(new NameValueHeaderValue("boundary", boundary));
        var handler = new TestHttpMessageHandler(_ => response);
        var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.com/graphql"));
        var operation = Substitute.For<global::GraphQL.Sharp.Generated.IGraphQLOperation<DummyResponse, DummyVariables>>();
        operation.OperationName.Returns("TestOp");
        operation.Query.Returns("query TestOp { __typename }");
        operation.Variables.Returns((DummyVariables? )null);
        var results = new List<GraphQLResponse<DummyResponse>>();
        await foreach (var item in client.ExecuteIncrementalAsync(operation, TestContext.Current.CancellationToken))
        {
            results.Add(item);
        }

        results.Count.ShouldBe(2);
    }

    [Fact]
    public void GraphQLError_Defaults_Message()
    {
        var error = new GraphQLError();
        error.Message.ShouldBe(string.Empty);
        var response = new GraphQLResponse<DummyResponse>
        {
            Errors = new[]
            {
                error
            }
        };
        response.Errors.ShouldNotBeNull();
    }

    [Fact]
    public void GraphQLError_Deserializes_Details()
    {
        var json = """
{
  "errors": [
    {
      "message": "bad",
      "locations": [
        {
          "line": 2,
          "column": 4
        }
      ],
      "path": [
        "users",
        0,
        "name"
      ],
      "extensions": {
        "code": "BAD"
      }
    }
  ]
}
""";
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };
        var response = JsonSerializer.Deserialize<GraphQLResponse<DummyResponse>>(json, options);
        response.ShouldNotBeNull();
        response.Errors.ShouldNotBeNull();
        response.Errors!.Length.ShouldBe(1);
        var error = response.Errors[0];
        error.Message.ShouldBe("bad");
        error.Locations.ShouldNotBeNull();
        error.Locations![0].Line.ShouldBe(2);
        error.Locations[0].Column.ShouldBe(4);
        error.Path.ShouldNotBeNull();
        error.Path!.Length.ShouldBe(3);
        error.Path[0].GetString().ShouldBe("users");
        error.Path[1].GetInt32().ShouldBe(0);
        error.Path[2].GetString().ShouldBe("name");
        error.Extensions.ShouldNotBeNull();
        error.Extensions!.Value.GetProperty("code").GetString().ShouldBe("BAD");
    }

    [Fact]
    public void Response_Allows_Null_List_Items()
    {
        var json = """
{
  "data": {
    "posts": [
      null
    ]
  }
}
""";
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };
        var response = JsonSerializer.Deserialize<GraphQLResponse<DummyListResponse>>(json, options);
        response.ShouldNotBeNull();
        response.Data.ShouldNotBeNull();
        response.Data!.Posts.Count.ShouldBe(1);
        response.Data.Posts[0].ShouldBeNull();
    }

    [Fact]
    public void GraphQLResponse_Allows_Null_For_NonNull_Field_With_Errors()
    {
        var json = """
{
  "data": {
    "users": null
  },
  "errors": [
    {
      "message": "Non-null violation"
    }
  ]
}
""";
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };
        var response = JsonSerializer.Deserialize<GraphQLResponse<DummyUsersResponse>>(json, options);
        response.ShouldNotBeNull();
        response.Errors.ShouldNotBeNull();
        response.Data.ShouldNotBeNull();
        response.Data!.Users.ShouldBeNull();
    }

    [Fact]
    public void GraphQLResponse_Allows_Null_Data_With_Errors()
    {
        var json = """
{
  "data": null,
  "errors": [
    {
      "message": "Failure"
    }
  ]
}
""";
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };
        var response = JsonSerializer.Deserialize<GraphQLResponse<DummyUsersResponse>>(json, options);
        response.ShouldNotBeNull();
        response.Errors.ShouldNotBeNull();
        response.Data.ShouldBeNull();
    }

    [Fact]
    public async Task ExecuteAsync_Uses_Get_For_Query()
    {
        var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""
{
  "data": null
}
"""));
        var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.com/graphql"));
        var operation = Substitute.For<global::GraphQL.Sharp.Generated.IGraphQLOperation<DummyResponse, DummyVariables>>();
        operation.OperationName.Returns("TestOp");
        operation.Query.Returns("query TestOp { __typename }");
        operation.Variables.Returns((DummyVariables? )null);
        await client.ExecuteAsync(operation, TestContext.Current.CancellationToken);
        var request = handler.LastRequest.ShouldNotBeNull();
        request.Method.ShouldBe(HttpMethod.Get);
        request.RequestUri.ShouldNotBeNull();
        request.RequestUri!.Query.ShouldContain("operationName=TestOp");
        request.RequestUri.Query.ShouldContain("query=");
    }

    [Fact]
    public async Task ExecuteBatchAsync_Sends_Array_Payload()
    {
        var handler = new TestHttpMessageHandler(_ => TestHttpMessageHandler.JsonResponse("""
[
  {
    "data": null
  },
  {
    "data": null
  }
]
"""));
        var httpClient = new HttpClient(handler);
        var client = new GraphQLClient(httpClient, new Uri("https://example.com/graphql"));
        var operation = Substitute.For<global::GraphQL.Sharp.Generated.IGraphQLOperation<DummyResponse, DummyVariables>>();
        operation.OperationName.Returns("TestOp");
        operation.Query.Returns("query TestOp { __typename }");
        operation.Variables.Returns((DummyVariables? )null);
        await client.ExecuteBatchAsync(new[] { operation, operation }, TestContext.Current.CancellationToken);
        var payload = handler.ContentText.ShouldNotBeNull();
        using var document = JsonDocument.Parse(payload);
        document.RootElement.ValueKind.ShouldBe(JsonValueKind.Array);
        document.RootElement.GetArrayLength().ShouldBe(2);
    }
}
