// <auto-generated/>
#nullable enable
using GraphQL.Sharp.Generated;
using Shouldly;
using Xunit;

namespace Salep.Samples.MinimalDependencies.Client.Tests;
public sealed class OperationsMetadataTests
{
    [Fact]
    public void CreatePostSimple_Operation_Metadata()
    {
        var variables = new CreatePostSimpleVariables();
        var response = new CreatePostSimpleResponse();
        var operation = new CreatePostSimpleOperation(variables);
        operation.OperationName.ShouldBe("CreatePostSimple");
        operation.Query.ShouldContain("CreatePostSimple");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void CreatePostWithContent_Operation_Metadata()
    {
        var variables = new CreatePostWithContentVariables();
        var response = new CreatePostWithContentResponse();
        var operation = new CreatePostWithContentOperation(variables);
        operation.OperationName.ShouldBe("CreatePostWithContent");
        operation.Query.ShouldContain("CreatePostWithContent");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void CreatePostAliased_Operation_Metadata()
    {
        var variables = new CreatePostAliasedVariables();
        var response = new CreatePostAliasedResponse();
        var operation = new CreatePostAliasedOperation(variables);
        operation.OperationName.ShouldBe("CreatePostAliased");
        operation.Query.ShouldContain("CreatePostAliased");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void UpdatePostWithDefaults_Operation_Metadata()
    {
        var variables = new UpdatePostWithDefaultsVariables();
        var response = new UpdatePostWithDefaultsResponse();
        var operation = new UpdatePostWithDefaultsOperation(variables);
        operation.OperationName.ShouldBe("UpdatePostWithDefaults");
        operation.Query.ShouldContain("UpdatePostWithDefaults");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void DeletePosts_Operation_Metadata()
    {
        var variables = new DeletePostsVariables();
        var response = new DeletePostsResponse();
        var operation = new DeletePostsOperation(variables);
        operation.OperationName.ShouldBe("DeletePosts");
        operation.Query.ShouldContain("DeletePosts");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void UsersDefaultRole_Operation_Metadata()
    {
        var variables = new UsersDefaultRoleVariables();
        var response = new UsersDefaultRoleResponse();
        var operation = new UsersDefaultRoleOperation(variables);
        operation.OperationName.ShouldBe("UsersDefaultRole");
        operation.Query.ShouldContain("UsersDefaultRole");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void UsersByRole_Operation_Metadata()
    {
        var variables = new UsersByRoleVariables();
        var response = new UsersByRoleResponse();
        var operation = new UsersByRoleOperation(variables);
        operation.OperationName.ShouldBe("UsersByRole");
        operation.Query.ShouldContain("UsersByRole");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void UsersByRole_Omits_Variable_Definition()
    {
        var operation = new UsersByRoleOperation();
        System.Text.RegularExpressions.Regex.IsMatch(operation.Query, "\\$ids(?![_0-9A-Za-z])").ShouldBeFalse();
    }

    [Fact]
    public void SearchUsersAndPosts_Operation_Metadata()
    {
        var variables = new SearchUsersAndPostsVariables();
        var response = new SearchUsersAndPostsResponse();
        var operation = new SearchUsersAndPostsOperation(variables);
        operation.OperationName.ShouldBe("SearchUsersAndPosts");
        operation.Query.ShouldContain("SearchUsersAndPosts");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void NodeById_Operation_Metadata()
    {
        var variables = new NodeByIdVariables();
        var response = new NodeByIdResponse();
        var operation = new NodeByIdOperation(variables);
        operation.OperationName.ShouldBe("NodeById");
        operation.Query.ShouldContain("NodeById");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void SearchWithMultipleInlineFragments_Operation_Metadata()
    {
        var variables = new SearchWithMultipleInlineFragmentsVariables();
        var response = new SearchWithMultipleInlineFragmentsResponse();
        var operation = new SearchWithMultipleInlineFragmentsOperation(variables);
        operation.OperationName.ShouldBe("SearchWithMultipleInlineFragments");
        operation.Query.ShouldContain("SearchWithMultipleInlineFragments");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void EchoList_Operation_Metadata()
    {
        var variables = new EchoListVariables();
        var response = new EchoListResponse();
        var operation = new EchoListOperation(variables);
        operation.OperationName.ShouldBe("EchoList");
        operation.Query.ShouldContain("EchoList");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void EchoList_Omits_Variable_Definition()
    {
        var operation = new EchoListOperation();
        System.Text.RegularExpressions.Regex.IsMatch(operation.Query, "\\$single(?![_0-9A-Za-z])").ShouldBeFalse();
        System.Text.RegularExpressions.Regex.IsMatch(operation.Query, "\\$options(?![_0-9A-Za-z])").ShouldBeFalse();
    }

    [Fact]
    public void PostsByIds_Operation_Metadata()
    {
        var variables = new PostsByIdsVariables();
        var response = new PostsByIdsResponse();
        var operation = new PostsByIdsOperation(variables);
        operation.OperationName.ShouldBe("PostsByIds");
        operation.Query.ShouldContain("PostsByIds");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void UnusedVar_Operation_Metadata()
    {
        var variables = new UnusedVarVariables();
        var response = new UnusedVarResponse();
        var operation = new UnusedVarOperation(variables);
        operation.OperationName.ShouldBe("UnusedVar");
        operation.Query.ShouldContain("UnusedVar");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void UnusedVar_Omits_Variable_Definition()
    {
        var operation = new UnusedVarOperation();
        System.Text.RegularExpressions.Regex.IsMatch(operation.Query, "\\$unused(?![_0-9A-Za-z])").ShouldBeFalse();
    }

    [Fact]
    public void PostCreatedFull_Operation_Metadata()
    {
        var variables = new PostCreatedFullVariables();
        var response = new PostCreatedFullResponse();
        var operation = new PostCreatedFullOperation(variables);
        operation.OperationName.ShouldBe("PostCreatedFull");
        operation.Query.ShouldContain("PostCreatedFull");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void PostCreatedMinimal_Operation_Metadata()
    {
        var variables = new PostCreatedMinimalVariables();
        var response = new PostCreatedMinimalResponse();
        var operation = new PostCreatedMinimalOperation(variables);
        operation.OperationName.ShouldBe("PostCreatedMinimal");
        operation.Query.ShouldContain("PostCreatedMinimal");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }

    [Fact]
    public void CommentAdded_Operation_Metadata()
    {
        var variables = new CommentAddedVariables();
        var response = new CommentAddedResponse();
        var operation = new CommentAddedOperation(variables);
        operation.OperationName.ShouldBe("CommentAdded");
        operation.Query.ShouldContain("CommentAdded");
        operation.Variables.ShouldBeSameAs(variables);
        response.ShouldNotBeNull();
    }
}
