<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <ProjectReference Include="../../src/Salep.GraphQLParser/Salep.GraphQLParser.csproj" />
    <None Include="../corpus/**/*" Link="corpus/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="allocation-budgets.v1.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
